import { Subject, ManualQuestion } from './types';

export const CURATED_STREAK_QUESTIONS: Record<Subject, ManualQuestion[]> = {
  Music: [
    {
      number: 1,
      text: 'Which musical term indicates a very slow tempo?',
      options: ['A. Allegro', 'B. Largo', 'C. Presto', 'D. Vivace'],
      correctAnswer: 'B',
    },
    {
      number: 2,
      text: 'How many semitones make up a perfect fifth interval?',
      options: ['A. 5 semitones', 'B. 6 semitones', 'C. 7 semitones', 'D. 8 semitones'],
      correctAnswer: 'C',
    },
    {
      number: 3,
      text: 'Which clef is also commonly known as the G clef?',
      options: ['A. Treble Clef', 'B. Bass Clef', 'C. Alto Clef', 'D. Tenor Clef'],
      correctAnswer: 'A',
    },
    {
      number: 4,
      text: 'Who composed the famous "Moonlight Sonata"?',
      options: ['A. Wolfgang Amadeus Mozart', 'B. Ludwig van Beethoven', 'C. Johann Sebastian Bach', 'D. Franz Schubert'],
      correctAnswer: 'B',
    },
    {
      number: 5,
      text: 'What note value is equal to half of a quarter note?',
      options: ['A. Eighth note', 'B. Half note', 'C. Whole note', 'D. Sixteenth note'],
      correctAnswer: 'A',
    },
    {
      number: 6,
      text: 'In standard 4/4 time, how many beats does a dotted half note receive?',
      options: ['A. 2 beats', 'B. 3 beats', 'C. 4 beats', 'D. 1.5 beats'],
      correctAnswer: 'B',
    },
    {
      number: 7,
      text: 'Which instrument family does the oboe belong to?',
      options: ['A. Brass', 'B. Strings', 'C. Woodwinds', 'D. Percussion'],
      correctAnswer: 'C',
    },
    {
      number: 8,
      text: 'What is the relative minor key of C major?',
      options: ['A. D minor', 'B. E minor', 'C. A minor', 'D. G minor'],
      correctAnswer: 'C',
    },
    {
      number: 9,
      text: 'What does the dynamic marking "pianissimo" (pp) mean?',
      options: ['A. Very loud', 'B. Moderately soft', 'C. Very soft', 'D. Gradually louder'],
      correctAnswer: 'C',
    },
    {
      number: 10,
      text: 'How many sharps are in the key signature of D major?',
      options: ['A. 1 sharp', 'B. 2 sharps', 'C. 3 sharps', 'D. 4 sharps'],
      correctAnswer: 'B',
    },
    {
      number: 11,
      text: 'Which Indian classical musical scale system is known as a parent scale?',
      options: ['A. Raga', 'B. Thaat', 'C. Tala', 'D. Gharana'],
      correctAnswer: 'B',
    },
    {
      number: 12,
      text: 'What is the standard concert pitch frequency for the note A4?',
      options: ['A. 432 Hz', 'B. 440 Hz', 'C. 444 Hz', 'D. 420 Hz'],
      correctAnswer: 'B',
    },
    {
      number: 13,
      text: 'Which Italian term directs musicians to play smoothly and connected?',
      options: ['A. Staccato', 'B. Legato', 'C. Pizzicato', 'D. Marcato'],
      correctAnswer: 'B',
    },
    {
      number: 14,
      text: 'Which of the following is a brass instrument that uses a slide rather than valves?',
      options: ['A. Trumpet', 'B. French Horn', 'C. Trombone', 'D. Tuba'],
      correctAnswer: 'C',
    },
    {
      number: 15,
      text: 'A chord composed of a root, minor third, and diminished fifth is called:',
      options: ['A. Major triad', 'B. Diminished triad', 'C. Augmented triad', 'D. Suspended triad'],
      correctAnswer: 'B',
    },
    {
      number: 16,
      text: 'What does the musical direction "Da Capo" (D.C.) mean?',
      options: ['A. From the sign', 'B. From the beginning', 'C. To the finish', 'D. Repeat measure'],
      correctAnswer: 'B',
    },
    {
      number: 17,
      text: 'How many strings does a standard classical concert harp typically have?',
      options: ['A. 47', 'B. 36', 'C. 52', 'D. 40'],
      correctAnswer: 'A',
    },
    {
      number: 18,
      text: 'Which period in music history followed the Renaissance and preceded the Classical period?',
      options: ['A. Romantic', 'B. Baroque', 'C. Medieval', 'D. Modern'],
      correctAnswer: 'B',
    },
    {
      number: 19,
      text: 'What is the time signature for a traditional waltz?',
      options: ['A. 4/4', 'B. 3/4', 'C. 2/4', 'D. 6/8'],
      correctAnswer: 'B',
    },
    {
      number: 20,
      text: 'What does the term "crescendo" instruct the performer to do?',
      options: ['A. Gradually get louder', 'B. Gradually get softer', 'C. Speed up', 'D. Slow down'],
      correctAnswer: 'A',
    },
  ],
  Math: [
    {
      number: 1,
      text: 'What is the derivative of f(x) = x^3 - 4x + 7 with respect to x?',
      options: ['A. 3x^2 - 4', 'B. 3x^2 - 4x', 'C. x^2 - 4', 'D. 3x^3 - 4'],
      correctAnswer: 'A',
    },
    {
      number: 2,
      text: 'What is the value of log10(1000)?',
      options: ['A. 2', 'B. 3', 'C. 10', 'D. 100'],
      correctAnswer: 'B',
    },
    {
      number: 3,
      text: 'If a triangle has sides of length 5 cm, 12 cm, and 13 cm, what is its area?',
      options: ['A. 60 cm²', 'B. 30 cm²', 'C. 65 cm²', 'D. 32.5 cm²'],
      correctAnswer: 'B',
    },
    {
      number: 4,
      text: 'What is the sum of interior angles in a regular hexagon?',
      options: ['A. 540°', 'B. 720°', 'C. 900°', 'D. 360°'],
      correctAnswer: 'B',
    },
    {
      number: 5,
      text: 'Solve for x: 2^(2x + 1) = 32.',
      options: ['A. 1', 'B. 2', 'C. 3', 'D. 4'],
      correctAnswer: 'B',
    },
    {
      number: 6,
      text: 'What is the value of sin²(45°) + cos²(45°)?',
      options: ['A. 0', 'B. 0.5', 'C. 1', 'D. 2'],
      correctAnswer: 'C',
    },
    {
      number: 7,
      text: 'What is the determinant of matrix [[3, 2], [1, 4]]?',
      options: ['A. 10', 'B. 12', 'C. 14', 'D. 8'],
      correctAnswer: 'A',
    },
    {
      number: 8,
      text: 'If the probability of an event is 0.35, what is the probability of its complement?',
      options: ['A. 0.35', 'B. 0.65', 'C. 0.75', 'D. 0.50'],
      correctAnswer: 'B',
    },
    {
      number: 9,
      text: 'What is the roots of the quadratic equation x² - 5x + 6 = 0?',
      options: ['A. 2 and 3', 'B. -2 and -3', 'C. 1 and 6', 'D. -1 and -6'],
      correctAnswer: 'A',
    },
    {
      number: 10,
      text: 'What is the slope of the line perpendicular to y = -2x + 5?',
      options: ['A. -2', 'B. 2', 'C. 1/2', 'D. -1/2'],
      correctAnswer: 'C',
    },
    {
      number: 11,
      text: 'What is the limit of (sin x) / x as x approaches 0?',
      options: ['A. 0', 'B. 1', 'C. Infinity', 'D. Undefined'],
      correctAnswer: 'B',
    },
    {
      number: 12,
      text: 'How many subsets does a set containing 5 distinct elements have?',
      options: ['A. 25', 'B. 32', 'C. 10', 'D. 16'],
      correctAnswer: 'B',
    },
    {
      number: 13,
      text: 'What is the mean of the numbers: 4, 8, 12, 16, 20?',
      options: ['A. 10', 'B. 12', 'C. 14', 'D. 16'],
      correctAnswer: 'B',
    },
    {
      number: 14,
      text: 'What is the formula for the volume of a sphere of radius r?',
      options: ['A. (4/3)πr³', 'B. 4πr²', 'C. (2/3)πr³', 'D. πr²h'],
      correctAnswer: 'A',
    },
    {
      number: 15,
      text: 'What is the value of 5! (5 factorial)?',
      options: ['A. 24', 'B. 60', 'C. 120', 'D. 720'],
      correctAnswer: 'C',
    },
    {
      number: 16,
      text: 'In an arithmetic progression with first term a = 3 and common difference d = 4, what is the 10th term?',
      options: ['A. 36', 'B. 39', 'C. 40', 'D. 43'],
      correctAnswer: 'B',
    },
    {
      number: 17,
      text: 'What is the distance between the points (1, 2) and (4, 6)?',
      options: ['A. 4', 'B. 5', 'C. 6', 'D. 7'],
      correctAnswer: 'B',
    },
    {
      number: 18,
      text: 'Which of the following numbers is an irrational number?',
      options: ['A. 3.14', 'B. 22/7', 'C. √2', 'D. √9'],
      correctAnswer: 'C',
    },
    {
      number: 19,
      text: 'What is the value of cos(0°)?',
      options: ['A. 0', 'B. 0.5', 'C. 1', 'D. -1'],
      correctAnswer: 'C',
    },
    {
      number: 20,
      text: 'What is the product of (x + 3) and (x - 3)?',
      options: ['A. x² + 9', 'B. x² - 9', 'C. x² - 6x + 9', 'D. x² + 6x - 9'],
      correctAnswer: 'B',
    },
  ],
  History: [
    {
      number: 1,
      text: 'In which year did the Battle of Plassey take place?',
      options: ['A. 1757', 'B. 1764', 'C. 1857', 'D. 1748'],
      correctAnswer: 'A',
    },
    {
      number: 2,
      text: 'Who was the founder of the Maurya Empire in ancient India?',
      options: ['A. Ashoka', 'B. Chandragupta Maurya', 'C. Bindusara', 'D. Samudragupta'],
      correctAnswer: 'B',
    },
    {
      number: 3,
      text: 'Which treaty ended World War I in 1919?',
      options: ['A. Treaty of Paris', 'B. Treaty of Versailles', 'C. Treaty of Ghent', 'D. Treaty of Vienna'],
      correctAnswer: 'B',
    },
    {
      number: 4,
      text: 'The Indus Valley Civilization site "Harappa" is located near which river?',
      options: ['A. Indus', 'B. Ravi', 'C. Jhelum', 'D. Ghaggar'],
      correctAnswer: 'B',
    },
    {
      number: 5,
      text: 'Who was the first President of the United States?',
      options: ['A. Thomas Jefferson', 'B. George Washington', 'C. John Adams', 'D. Abraham Lincoln'],
      correctAnswer: 'B',
    },
    {
      number: 6,
      text: 'The French Revolution began with the storming of which fortress in 1789?',
      options: ['A. Bastille', 'B. Versailles', 'C. Louvre', 'D. Tuileries'],
      correctAnswer: 'A',
    },
    {
      number: 7,
      text: 'Who was known as the "Iron Man of India"?',
      options: ['A. Jawaharlal Nehru', 'B. Sardar Vallabhbhai Patel', 'C. Subhas Chandra Bose', 'D. Bhagat Singh'],
      correctAnswer: 'B',
    },
    {
      number: 8,
      text: 'In which year did the Dandi March (Salt Satyagraha) take place?',
      options: ['A. 1920', 'B. 1930', 'C. 1942', 'D. 1919'],
      correctAnswer: 'B',
    },
    {
      number: 9,
      text: 'Who built the famous Grand Trunk Road connecting Eastern and Western parts of the subcontinent?',
      options: ['A. Akbar', 'B. Sher Shah Suri', 'C. Shah Jahan', 'D. Babur'],
      correctAnswer: 'B',
    },
    {
      number: 10,
      text: 'Which ancient Greek philosopher was the teacher of Alexander the Great?',
      options: ['A. Socrates', 'B. Plato', 'C. Aristotle', 'D. Pythagoras'],
      correctAnswer: 'C',
    },
    {
      number: 11,
      text: 'The Magna Carta was signed in which year by King John of England?',
      options: ['A. 1066', 'B. 1215', 'C. 1492', 'D. 1600'],
      correctAnswer: 'B',
    },
    {
      number: 12,
      text: 'Who was the first woman Prime Minister of India?',
      options: ['A. Sarojini Naidu', 'B. Indira Gandhi', 'C. Sucheta Kripalani', 'D. Pratibha Patil'],
      correctAnswer: 'B',
    },
    {
      number: 13,
      text: 'Which Mughal Emperor shifted the capital from Agra to Delhi?',
      options: ['A. Jahangir', 'B. Shah Jahan', 'C. Aurangzeb', 'D. Humayun'],
      correctAnswer: 'B',
    },
    {
      number: 14,
      text: 'The United Nations was officially founded in which year?',
      options: ['A. 1919', 'B. 1945', 'C. 1950', 'D. 1939'],
      correctAnswer: 'B',
    },
    {
      number: 15,
      text: 'Who was the author of the ancient Indian treatise on statecraft "Arthashastra"?',
      options: ['A. Kalidasa', 'B. Chanakya (Kautilya)', 'C. Banabhatta', 'D. Aryabhata'],
      correctAnswer: 'B',
    },
    {
      number: 16,
      text: 'In which year did the Fall of the Berlin Wall occur?',
      options: ['A. 1989', 'B. 1991', 'C. 1975', 'D. 1985'],
      correctAnswer: 'A',
    },
    {
      number: 17,
      text: 'Who founded the Brahmo Samaj in 1828?',
      options: ['A. Swami Vivekananda', 'B. Raja Ram Mohan Roy', 'C. Dayananda Saraswati', 'D. Ishwar Chandra Vidyasagar'],
      correctAnswer: 'B',
    },
    {
      number: 18,
      text: 'Which revolution overthrew the Russian monarchy in 1917?',
      options: ['A. Bolshevik Revolution', 'B. Industrial Revolution', 'C. Glorious Revolution', 'D. Velvet Revolution'],
      correctAnswer: 'A',
    },
    {
      number: 19,
      text: 'The Renaissance movement originated in which country?',
      options: ['A. France', 'B. Italy', 'C. Germany', 'D. England'],
      correctAnswer: 'B',
    },
    {
      number: 20,
      text: 'Who gave the slogan "Give me blood, and I shall give you freedom!"?',
      options: ['A. Mahatma Gandhi', 'B. Subhas Chandra Bose', 'C. Bhagat Singh', 'D. Bal Gangadhar Tilak'],
      correctAnswer: 'B',
    },
  ],
  Geography: [
    {
      number: 1,
      text: 'What is the longest river in the world?',
      options: ['A. Amazon River', 'B. Nile River', 'C. Yangtze River', 'D. Mississippi River'],
      correctAnswer: 'B',
    },
    {
      number: 2,
      text: 'Which layer of the atmosphere contains the ozone layer?',
      options: ['A. Troposphere', 'B. Stratosphere', 'C. Mesosphere', 'D. Thermosphere'],
      correctAnswer: 'B',
    },
    {
      number: 3,
      text: 'What is the capital city of Australia?',
      options: ['A. Sydney', 'B. Melbourne', 'C. Canberra', 'D. Brisbane'],
      correctAnswer: 'C',
    },
    {
      number: 4,
      text: 'Which strait connects the Pacific Ocean and the Arctic Ocean?',
      options: ['A. Strait of Gibraltar', 'B. Bering Strait', 'C. Strait of Malacca', 'D. Bosporus Strait'],
      correctAnswer: 'B',
    },
    {
      number: 5,
      text: 'Which is the largest desert in the world by area (including polar deserts)?',
      options: ['A. Sahara Desert', 'B. Arabian Desert', 'C. Antarctic Desert', 'D. Gobi Desert'],
      correctAnswer: 'C',
    },
    {
      number: 6,
      text: 'What is the highest mountain peak in North America?',
      options: ['A. Mount Whitney', 'B. Mount Denali (McKinley)', 'C. Mount Logan', 'D. Mount Rainier'],
      correctAnswer: 'B',
    },
    {
      number: 7,
      text: 'The Tropic of Cancer passes through which of the following continents?',
      options: ['A. South America, Africa, Australia', 'B. North America, Africa, Asia', 'C. Europe, Asia, Africa', 'D. North America, South America, Asia'],
      correctAnswer: 'B',
    },
    {
      number: 8,
      text: 'Which European country has the most natural lakes?',
      options: ['A. Sweden', 'B. Finland', 'C. Norway', 'D. Switzerland'],
      correctAnswer: 'B',
    },
    {
      number: 9,
      text: 'What type of plate boundary creates deep ocean trenches and volcanic arcs?',
      options: ['A. Divergent boundary', 'B. Convergent boundary (Subduction)', 'C. Transform boundary', 'D. Continental rift'],
      correctAnswer: 'B',
    },
    {
      number: 10,
      text: 'Which is the deepest lake in the world?',
      options: ['A. Lake Superior', 'B. Lake Baikal', 'C. Lake Victoria', 'D. Lake Tanganyika'],
      correctAnswer: 'B',
    },
    {
      number: 11,
      text: 'What is the line of longitude that marks 0 degrees called?',
      options: ['A. Equator', 'B. Prime Meridian', 'C. International Date Line', 'D. Tropic of Capricorn'],
      correctAnswer: 'B',
    },
    {
      number: 12,
      text: 'Which sea is located between Jordan and Israel and is known for its high salinity?',
      options: ['A. Red Sea', 'B. Dead Sea', 'C. Caspian Sea', 'D. Black Sea'],
      correctAnswer: 'B',
    },
    {
      number: 13,
      text: 'Which African country is known as the "Horn of Africa"?',
      options: ['A. Kenya', 'B. Somalia', 'C. Egypt', 'D. South Africa'],
      correctAnswer: 'B',
    },
    {
      number: 14,
      text: 'What is the predominant mineral component in the Earth\'s continental crust?',
      options: ['A. Iron', 'B. Silicon and Aluminum (Sial)', 'C. Magnesium and Nickel', 'D. Calcium carbonate'],
      correctAnswer: 'B',
    },
    {
      number: 15,
      text: 'Which is the largest island in the world that is not a continent?',
      options: ['A. Madagascar', 'B. Greenland', 'C. New Guinea', 'D. Borneo'],
      correctAnswer: 'B',
    },
    {
      number: 16,
      text: 'The Mariana Trench is located in which ocean?',
      options: ['A. Atlantic Ocean', 'B. Indian Ocean', 'C. Pacific Ocean', 'D. Arctic Ocean'],
      correctAnswer: 'C',
    },
    {
      number: 17,
      text: 'Which biome is characterized by permafrost, low biodiversity, and short growing seasons?',
      options: ['A. Taiga', 'B. Tundra', 'C. Savanna', 'D. Temperate Deciduous'],
      correctAnswer: 'B',
    },
    {
      number: 18,
      text: 'What is the capital of Canada?',
      options: ['A. Toronto', 'B. Vancouver', 'C. Ottawa', 'D. Montreal'],
      correctAnswer: 'C',
    },
    {
      number: 19,
      text: 'Which volcano famously destroyed the ancient city of Pompeii in 79 AD?',
      options: ['A. Mount Etna', 'B. Mount Vesuvius', 'C. Mount Stromboli', 'D. Mount Olympus'],
      correctAnswer: 'B',
    },
    {
      number: 20,
      text: 'What is the phenomenon where trade winds weaken, causing unusually warm Pacific ocean temperatures?',
      options: ['A. La Niña', 'B. El Niño', 'C. Monsoon reversal', 'D. Gulf Stream shift'],
      correctAnswer: 'B',
    },
  ],
};
